<?php
/**
 * @author Atwix Team
 * @copyright Copyright (c) 2017 Atwix (https://www.atwix.com/)
 * @package Atwix_PHPUnitSample
 */

namespace Atwix\PHPUnitSample\Dummy;

/**
 * Class AutoGenerated
 */
class AutoGenerated
{
    /** @var \Magento\Customer\Api\Data\AddressInterfaceFactory */
    protected $addressFactory;

    /**
     * @param \Magento\Customer\Api\Data\AddressInterfaceFactory $addressFactory
     */
    public function __construct(
        \Magento\Customer\Api\Data\AddressInterfaceFactory $addressFactory
    ) {
        $this->addressFactory = $addressFactory;
    }

    /**
     * @return \Magento\Customer\Api\Data\AddressInterface
     */
    public function execute()
    {
        $address = $this->addressFactory->create();

        return $address;
    }
}